"""empty message

Revision ID: 25be7817bac5
Revises: 59a2b9b5d3cc
Create Date: 2023-11-28 17:55:30.347105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25be7817bac5'
down_revision = '59a2b9b5d3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishview', schema=None) as batch_op:
        batch_op.alter_column('dish_image_url',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('user.id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dishview.id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('dishview.id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user.id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dishview', schema=None) as batch_op:
        batch_op.alter_column('dish_image_url',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
