"""empty message

Revision ID: 4bafed78a2e3
Revises: 104d8ca0d95a
Create Date: 2023-11-22 15:44:18.125325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bafed78a2e3'
down_revision = '104d8ca0d95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishview', schema=None) as batch_op:
        batch_op.alter_column('dish_image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishview', schema=None) as batch_op:
        batch_op.alter_column('dish_image_url',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
